### ISSUE TITLE
Release pipeline and first release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-hk2-extra#6]
We need to create a release CI/CD pipeline for this project and release the first version from Eclipse. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by ankathur** [comment]
Release job for osgi-resource-locator is created https://jenkins.eclipse.org/glassfish/job/osgi-resource-locator-release-job/ and artifacts are released to OSSRH.

**Comment by ankathur** [comment]
We are releasing osgi-resource-locator only from hk2-extra.
