### ISSUE TITLE
Current source?

### ISSUE THREAD

**Issue by mnlipp** [eclipse-ee4j/glassfish-hk2-extra#61]
There's a version 2.5.0-b42 of the OSGi resource locator in maven central. The latest tag here is 1.0.3. Can anybody please tell me where I can find the current source code?

**Comment by pzygielo** [comment]
This is a channel to report bugs.
For questions please use https://github.com/eclipse-ee4j/glassfish-hk2-extra/blob/master/CONTRIBUTING.md#contact

However, as I'm already here...

https://repo.maven.apache.org/maven2/org/glassfish/hk2/osgi-resource-locator/
```
1.0.3/                                            2019-01-03 12:15         -
2.5.0-b42/                                        2017-07-11 01:04         -
```

I suppose that:
- 1.0.3 WAS produced from this repository, and should match the tag present here
- 2.5.0-b42 was produced **before** donation to Eclipse, probably from https://github.com/javaee/hk2, as url from https://repo.maven.apache.org/maven2/org/glassfish/hk2/hk2-parent/2.5.0-b42/hk2-parent-2.5.0-b42.pom redirects there

> where I can find the current source code?

This is the currently maintained repository.

**Comment by mnlipp** [comment]
Thank you very much for the clarification! The newer version having a smaller major version number than the older one is, well, a bit unusual.

---

> This is a channel to report bugs. For questions please use https://github.com/eclipse-ee4j/glassfish-hk2-extra/blob/master/CONTRIBUTING.md#contact

Sorry for the misuse. Many low traffic projects use "Issues" for all communication. You have to admit that "Contributing" isn't the first place to look at if you have a question. Maybe move/copy the information about the mailing list to the "README.md".

**Comment by pzygielo** [comment]
> The newer version having a smaller major version number than the older one is, well, a bit unusual.

That's why I opened #62. I was also surprised that lower version was used within the same groupId. Hope some commiter will share the concern.
