### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-hk2-extra#8]
- [x] Uptake new Eclipse versions of dependencies. Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [x] Release to OSSRH staging repository

- [x] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number. 

[How to release first versions of EE4J components](https://wiki.eclipse.org/How_to_release_first_versions_of_EE4J_components)

**Comment by romain-grecourt** [comment]
The osgi-resource-locator used by HK2/GlassFish is hardcoded to 1.0.1 for a long time.
Unless we plan on integrating the new eclipse made artifact of osgi-resource-locator in HK2 and GF there is no point in releasing this repository.

**Comment by m0mus** [comment]
This is exactly the idea: release everything transferred to Eclipse and integrate it to Eclipse GlassFish. Are there any reasons other than hardcoded old version not integrating this version of osgi-resource-locator? Did we try integrating it?

**Comment by romain-grecourt** [comment]
There are historical reasons for the hardcoded version, I don't recall the exact details.
My point is that if we release this repository we must integrate the new osgi-resource-locator version, otherwise this is useless.

**Comment by m0mus** [comment]
@romain-grecourt I agree. There is https://github.com/eclipse-ee4j/glassfish-hk2-extra/issues/9 for it. I see that the artifact is released: https://oss.sonatype.org/content/groups/staging/org/glassfish/hk2/osgi-resource-locator/1.0.3/
Closing this issue.
